module.exports.obj={
    details:{
      name:{
        firstName:null,
        lastName:null
      },
      gender:null,
      dob:null,
      email:null,
      mobile:null,
      address:{
       fullAddress:null,
       pincode:null,
       state:null,
       country:null
     },
     fatherName:null,
     motherName:null,
     martialStatus:null,
     nationality:null,
     uniqueID:null,
     licenseNumber:null,
     passportNumber:null,
     panNumber:null,
     visaStatus:null
    },
      technicalSkills:null,
      skills:null,
      extraSkills:null,
      project:null,
      professionalExperience:null,
      careerObjective:null,
      academicQualifications:null,
      languages:null,
      hobbies:null,
      miscellaneous:null

 }
